"""
Word report — mirrors the dashboard's 5-section pattern:
Overview → Time → Person → Place → Exposure/Analytic → Conclusions
"""

from __future__ import annotations

import base64
import io
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

# ── Bilingual strings ──────────────────────────────────────────────────────────
S: dict[str, dict[str, str]] = {
    "en": {
        # cover
        "title":            "Outbreak Investigation Report",
        "generated_by":     "Generated by BananaEpi",
        "dataset":          "Dataset",
        "total_records":    "Total records",
        "case_def":         "Case definition",
        "exposure_vars":    "Exposure variables",
        # section headings
        "s1":               "1. Overview",
        "s2":               "2. Time Distribution",
        "s3":               "3. Person Characteristics",
        "s3_1":             "3.1  Sex",
        "s3_2":             "3.2  Age Group",
        "s3_3":             "3.3  Other Demographics",
        "s3_4":             "3.4  Symptoms",
        "s3_5":             "3.5  Clinical Outcomes",
        "s4":               "4. Place Distribution",
        "s5":               "5. Exposure & Risk Analysis",
        "s5_rr":            "5.1  Risk Ratio Summary",
        "s6":               "6. Conclusions & Recommendations",
        # overview metrics table
        "metric":           "Indicator",
        "value":            "Value",
        "total_invest":     "Total investigated",
        "cases_ar":         "Confirmed cases (attack rate)",
        "outbreak_period":  "Outbreak period",
        "days":             "days",
        "peak_date":        "Peak date",
        "median_age_lbl":   "Median age",
        "yrs":              "years",
        "iqr":              "IQR",
        "hosp_lbl":         "Hospitalised",
        "deaths_lbl":       "Deaths",
        "lab_conf_lbl":     "Lab-confirmed",
        "top_exp_lbl":      "Leading exposure",
        # time section
        "s2_timeline":      "Outbreak Timeline",
        "first_onset":      "First onset",
        "peak_onset":       "Peak onset",
        "last_onset":       "Last onset",
        "duration":         "Duration",
        "missing_onset":    "Missing onset date",
        "cases_lbl":        "cases",
        # person tables
        "sex":              "Sex",
        "age_group":        "Age Group",
        "occupation":       "Occupation",
        "nationality":      "Nationality",
        "cases":            "Cases",
        "total":            "Total",
        "ar":               "Attack Rate (%)",
        "symptom":          "Symptom",
        "pct_cases":        "% of Cases",
        "outcome":          "Outcome",
        "pct":              "%",
        # place
        "location":         "Location",
        "non_cases":        "Non-cases",
        "unknown":          "Unknown",
        # exposure table
        "exposure":         "Exposure",
        "exp_cases":        "Exp. Cases",
        "exp_total":        "Exp. Total",
        "ar_exp":           "AR Exp. (%)",
        "unexp_cases":      "Unexp. Cases",
        "unexp_total":      "Unexp. Total",
        "ar_unexp":         "AR Unexp. (%)",
        "rr":               "RR",
        "ci_95":            "95% CI",
        "p_val":            "P-value",
        "sig":              "Sig.",
        "n_analyzed":       "{n} exposure factor(s) analysed; {sig} statistically significant (p < 0.05).",
        "sig_note":         "* p < 0.05",
        # figures
        "fig_epicurve":     "Figure: Epidemic curve — cases by date of symptom onset.",
        "fig_pyramid":      "Figure: Age–sex pyramid.",
        "fig_symptoms":     "Figure: Symptom frequency among confirmed cases.",
        "fig_ar":           "Figure: Attack rates (%) — exposed vs unexposed.",
        "fig_forest":       "Figure: Forest plot of Risk Ratios with 95% confidence intervals.",
        # conclusions
        "concl_sig":        "The following {n} exposure(s) showed statistically significant associations:",
        "rr_bullet":        "{exposure}: RR = {rr} (95% CI {lo}–{hi}, p = {p})",
        "ctrl_measures":    "These findings should inform immediate control measures: removal of implicated items, enhanced inspections, and case-contact tracing.",
        "no_sig":           "No statistically significant exposure associations were identified (α = 0.05). Consider expanding case-finding, reviewing the case definition, or collecting additional exposure data.",
        "no_analytic":      "No analytic results available.",
        "disclaimer":       "This report was generated automatically by BananaEpi. All findings must be reviewed by a qualified epidemiologist before public health action is taken.",
    },
    "th": {
        # cover
        "title":            "รายงานการสอบสวนการระบาด",
        "generated_by":     "สร้างโดย BananaEpi",
        "dataset":          "ชุดข้อมูล",
        "total_records":    "จำนวนแถวทั้งหมด",
        "case_def":         "นิยามผู้ป่วย",
        "exposure_vars":    "ตัวแปรการสัมผัส",
        # section headings
        "s1":               "1. ภาพรวม",
        "s2":               "2. การกระจายตามเวลา",
        "s3":               "3. ลักษณะผู้ป่วย",
        "s3_1":             "3.1  เพศ",
        "s3_2":             "3.2  กลุ่มอายุ",
        "s3_3":             "3.3  ข้อมูลส่วนตัวอื่น ๆ",
        "s3_4":             "3.4  อาการ",
        "s3_5":             "3.5  ผลลัพธ์ทางคลินิก",
        "s4":               "4. การกระจายตามสถานที่",
        "s5":               "5. การวิเคราะห์ปัจจัยเสี่ยง",
        "s5_rr":            "5.1  ตารางสรุป Risk Ratio",
        "s6":               "6. สรุปและข้อเสนอแนะ",
        # overview metrics table
        "metric":           "ตัวชี้วัด",
        "value":            "ค่า",
        "total_invest":     "จำนวนผู้เข้ารับการสอบสวน",
        "cases_ar":         "ผู้ป่วยตามนิยาม (อัตราป่วย)",
        "outbreak_period":  "ช่วงเวลาการระบาด",
        "days":             "วัน",
        "peak_date":        "วันที่มีผู้ป่วยสูงสุด",
        "median_age_lbl":   "อายุมัธยฐาน",
        "yrs":              "ปี",
        "iqr":              "IQR",
        "hosp_lbl":         "รับไว้ในโรงพยาบาล",
        "deaths_lbl":       "เสียชีวิต",
        "lab_conf_lbl":     "ยืนยันทางห้องปฏิบัติการ",
        "top_exp_lbl":      "ปัจจัยเสี่ยงสำคัญ",
        # time section
        "s2_timeline":      "ไทม์ไลน์การระบาด",
        "first_onset":      "วันที่เริ่มป่วยรายแรก",
        "peak_onset":       "วันที่มีผู้ป่วยมากที่สุด",
        "last_onset":       "วันที่เริ่มป่วยรายสุดท้าย",
        "duration":         "ระยะเวลาการระบาด",
        "missing_onset":    "ผู้ป่วยที่ไม่มีวันที่เริ่มป่วย",
        "cases_lbl":        "ราย",
        # person tables
        "sex":              "เพศ",
        "age_group":        "กลุ่มอายุ",
        "occupation":       "อาชีพ",
        "nationality":      "สัญชาติ",
        "cases":            "จำนวนผู้ป่วย",
        "total":            "ทั้งหมด",
        "ar":               "อัตราป่วย (%)",
        "symptom":          "อาการ",
        "pct_cases":        "ร้อยละในผู้ป่วย",
        "outcome":          "ผลลัพธ์",
        "pct":              "ร้อยละ",
        # place
        "location":         "สถานที่",
        "non_cases":        "ไม่ป่วย",
        "unknown":          "ไม่ทราบ",
        # exposure table
        "exposure":         "ปัจจัยสัมผัส",
        "exp_cases":        "ป่วย (สัมผัส)",
        "exp_total":        "รวม (สัมผัส)",
        "ar_exp":           "อัตราป่วย สัมผัส (%)",
        "unexp_cases":      "ป่วย (ไม่สัมผัส)",
        "unexp_total":      "รวม (ไม่สัมผัส)",
        "ar_unexp":         "อัตราป่วย ไม่สัมผัส (%)",
        "rr":               "RR",
        "ci_95":            "ช่วงความเชื่อมั่น 95%",
        "p_val":            "ค่า p",
        "sig":              "มีนัยสำคัญ",
        "n_analyzed":       "วิเคราะห์ปัจจัยสัมผัสทั้งสิ้น {n} ปัจจัย พบ {sig} ปัจจัยมีนัยสำคัญทางสถิติ (p < 0.05)",
        "sig_note":         "* p < 0.05",
        # figures
        "fig_epicurve":     "รูป: เส้นโค้งระบาด — จำนวนผู้ป่วยตามวันที่เริ่มป่วย",
        "fig_pyramid":      "รูป: แผนภูมิพีระมิดอายุ-เพศ",
        "fig_symptoms":     "รูป: ความถี่อาการในผู้ป่วย",
        "fig_ar":           "รูป: อัตราป่วย (%) ในกลุ่มสัมผัสและไม่สัมผัส",
        "fig_forest":       "รูป: Forest plot ของ Risk Ratio พร้อมช่วงความเชื่อมั่น 95%",
        # conclusions
        "concl_sig":        "ปัจจัยสัมผัสต่อไปนี้จำนวน {n} ปัจจัยมีความสัมพันธ์กับการป่วยอย่างมีนัยสำคัญ",
        "rr_bullet":        "{exposure}: RR = {rr} (ช่วงความเชื่อมั่น 95% {lo}–{hi}, p = {p})",
        "ctrl_measures":    "ผลการสอบสวนนี้ควรนำไปใช้กำหนดมาตรการควบคุมโรคทันที ได้แก่ การนำอาหารที่สงสัยออก การเพิ่มความเข้มงวดด้านสุขาภิบาล และการสอบสวนผู้สัมผัส",
        "no_sig":           "ไม่พบปัจจัยสัมผัสใดที่มีนัยสำคัญทางสถิติ (α = 0.05) ควรพิจารณาขยายการค้นหาผู้ป่วย ทบทวนนิยามผู้ป่วย หรือเก็บข้อมูลการสัมผัสเพิ่มเติม",
        "no_analytic":      "ไม่มีผลการวิเคราะห์",
        "disclaimer":       "รายงานนี้สร้างขึ้นโดยอัตโนมัติจาก BananaEpi ผลการวิเคราะห์ทั้งหมดต้องได้รับการทบทวนโดยนักระบาดวิทยาที่มีความเชี่ยวชาญก่อนนำไปดำเนินการ",
    },
}

# ── Colours ────────────────────────────────────────────────────────────────────
HEADING_COLOR  = RGBColor(0x1E, 0x40, 0xAF)   # blue-800
HEADER_FILL    = "DBEAFE"                       # blue-100
ALT_FILL       = "F8FAFC"                       # slate-50
SIG_FILL       = "FEF9C3"                       # yellow-100


# ── Low-level helpers ──────────────────────────────────────────────────────────

def _s(lang: str, key: str) -> str:
    return S.get(lang, S["en"]).get(key, S["en"].get(key, key))


def _fmt(val: Any, decimals: int = 2) -> str:
    if val is None:
        return "—"
    if isinstance(val, float):
        return f"{val:.{decimals}f}"
    return str(val)


def _fmt_p(val: Any) -> str:
    if val is None:
        return "—"
    if isinstance(val, str):
        return val
    if val < 0.001:
        return "<0.001"
    return f"{val:.3f}"


def _cell_shd(cell, fill: str):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement("w:shd")
    shd.set(qn("w:val"),   "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"),  fill)
    tcPr.append(shd)


def _heading(doc: Document, text: str, level: int = 1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = HEADING_COLOR
    return h


def _para(doc: Document, text: str, italic: bool = False, size_pt: int | None = None,
          color: RGBColor | None = None):
    p = doc.add_paragraph(text)
    if p.runs:
        r = p.runs[0]
        if italic:
            r.italic = True
        if size_pt:
            r.font.size = Pt(size_pt)
        if color:
            r.font.color.rgb = color
    return p


def _kv_table(doc: Document, rows: list[tuple[str, str]]):
    """Two-column label/value table used for cover info and overview metrics."""
    tbl = doc.add_table(rows=len(rows), cols=2)
    tbl.style = "Table Grid"
    for i, (k, v) in enumerate(rows):
        tbl.rows[i].cells[0].text = k
        if tbl.rows[i].cells[0].paragraphs[0].runs:
            tbl.rows[i].cells[0].paragraphs[0].runs[0].bold = True
        tbl.rows[i].cells[1].text = str(v) if v is not None else "—"
        if i % 2 == 1:
            _cell_shd(tbl.rows[i].cells[0], ALT_FILL)
            _cell_shd(tbl.rows[i].cells[1], ALT_FILL)
    return tbl


def _data_table(doc: Document, headers: list[str], rows: list[list],
                sig_col: int | None = None):
    """Multi-column data table with blue header row and optional significant-row highlight."""
    tbl = doc.add_table(rows=1 + len(rows), cols=len(headers))
    tbl.style = "Table Grid"

    # header row
    for i, h in enumerate(headers):
        cell = tbl.rows[0].cells[i]
        cell.text = str(h)
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        if cell.paragraphs[0].runs:
            cell.paragraphs[0].runs[0].bold = True
        _cell_shd(cell, HEADER_FILL)

    # data rows
    for r_i, row in enumerate(rows):
        is_sig = sig_col is not None and r_i < len(rows) and str(rows[r_i][sig_col]).startswith("Yes")
        fill   = SIG_FILL if is_sig else (ALT_FILL if r_i % 2 == 1 else "FFFFFF")
        for c_i, val in enumerate(row):
            cell = tbl.rows[r_i + 1].cells[c_i]
            cell.text = str(val) if val is not None else "—"
            cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
            if fill != "FFFFFF":
                _cell_shd(cell, fill)

    return tbl


def _chart(doc: Document, b64: str | None, caption: str = ""):
    if not b64:
        return
    try:
        doc.add_picture(io.BytesIO(base64.b64decode(b64)), width=Inches(5.8))
        if caption:
            p = doc.add_paragraph(caption)
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            if p.runs:
                p.runs[0].italic = True
                p.runs[0].font.size = Pt(9)
    except Exception:
        pass


def _get_chart(charts: dict, key: str) -> str | None:
    return (charts.get(key) or {}).get("image_base64")


# ── Main builder ───────────────────────────────────────────────────────────────

def generate_word_report(
    metadata:     dict,
    dashboard:    dict,
    analytic_norm: list[dict],
    charts:       dict,
    output_path:  Path,
    lang:         str = "en",
) -> Path:
    doc = Document()

    def s(key: str) -> str:
        return _s(lang, key)

    ov   = dashboard.get("overview", {})
    time = dashboard.get("time",     {})
    pers = dashboard.get("person",   {})
    plc  = dashboard.get("place",    {})

    # ── COVER ─────────────────────────────────────────────────────────────────
    title_p = doc.add_heading(s("title"), 0)
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    ts  = datetime.now(timezone.utc).strftime("%d %B %Y  %H:%M UTC")
    sub = doc.add_paragraph(f"{s('generated_by')}  |  {ts}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if sub.runs:
        sub.runs[0].font.size = Pt(10)
        sub.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()

    active_cd = metadata.get("active_case_definition") or {}
    _kv_table(doc, [
        (s("dataset"),       metadata.get("original_filename", "—")),
        (s("total_records"), str(metadata.get("row_count", "—"))),
        (s("case_def"),      active_cd.get("case_definition_name", "—")),
        (s("exposure_vars"), str(len(metadata.get("exposure_columns", [])))),
    ])

    doc.add_page_break()

    # ── SECTION 1: OVERVIEW ───────────────────────────────────────────────────
    _heading(doc, s("s1"))

    # Key metrics summary table
    metrics: list[tuple[str, str]] = [
        (s("total_invest"),  str(ov.get("total_records", "—"))),
    ]

    case_count = ov.get("case_count")
    ar         = ov.get("attack_rate")
    if case_count is not None:
        ar_str = f" ({_fmt(ar, 1)}%)" if ar is not None else ""
        metrics.append((s("cases_ar"), f"{case_count}{ar_str}"))

    first = ov.get("first_onset")
    last  = ov.get("last_onset")
    dur   = ov.get("outbreak_duration_days")
    if first and last:
        dur_str = f" ({dur} {s('days')})" if dur is not None else ""
        metrics.append((s("outbreak_period"), f"{first} – {last}{dur_str}"))

    peak = ov.get("peak_onset_date")
    if peak:
        metrics.append((s("peak_date"), peak))

    med_age = ov.get("median_age")
    if med_age is not None:
        q1, q3 = ov.get("age_q1"), ov.get("age_q3")
        iqr_str = f"  ({s('iqr')}: {_fmt(q1, 0)}–{_fmt(q3, 0)} {s('yrs')})" if q1 else ""
        metrics.append((s("median_age_lbl"), f"{_fmt(med_age, 0)} {s('yrs')}{iqr_str}"))

    hosp      = ov.get("hospitalized_count")
    hosp_rate = ov.get("hospitalization_rate")
    if hosp is not None:
        rate_str = f" ({_fmt(hosp_rate, 1)}%)" if hosp_rate else ""
        metrics.append((s("hosp_lbl"), f"{hosp}{rate_str}"))

    deaths = ov.get("death_count")
    if deaths:
        metrics.append((s("deaths_lbl"), str(deaths)))

    lab = ov.get("lab_positive_count")
    lab_pct = ov.get("lab_positive_pct")
    if lab is not None:
        lab_str = f" ({_fmt(lab_pct, 1)}%)" if lab_pct else ""
        metrics.append((s("lab_conf_lbl"), f"{lab}{lab_str}"))

    top_exp = ov.get("top_exposure_signal")
    if top_exp:
        metrics.append((s("top_exp_lbl"), top_exp))

    _kv_table(doc, metrics)
    doc.add_paragraph()

    # Executive summary paragraph
    if lang == "en" and ov.get("summary"):
        _para(doc, ov["summary"])
    else:
        lines = []
        if case_count is not None and ov.get("total_records"):
            lines.append(
                f"มีผู้เข้ารับการสอบสวนทั้งสิ้น {ov['total_records']} ราย "
                f"ในจำนวนนี้ {case_count} รายตรงตามนิยามผู้ป่วย "
                f"(อัตราป่วยรวม {_fmt(ar, 1)}%)"
            )
        if first and last:
            pk = f" จุดสูงสุดวันที่ {peak}" if peak else ""
            lines.append(
                f"การระบาดครอบคลุมตั้งแต่วันที่ {first} ถึง {last}"
                f" (รวม {dur} วัน){pk}"
            )
        if med_age is not None:
            q1, q3 = ov.get("age_q1"), ov.get("age_q3")
            iqr_str = f" (IQR: {_fmt(q1, 0)}–{_fmt(q3, 0)} ปี)" if q1 else ""
            lines.append(f"อายุมัธยฐานของผู้ป่วยคือ {_fmt(med_age, 0)} ปี{iqr_str}")
        if hosp is not None:
            rate_str = f" (อัตราการรับไว้ {_fmt(hosp_rate, 1)}%)" if hosp_rate else ""
            lines.append(f"รับไว้ในโรงพยาบาล {hosp} ราย{rate_str}")
        if deaths:
            lines.append(f"เสียชีวิต {deaths} ราย")
        sym = ov.get("most_common_symptom")
        if sym:
            lines.append(f"อาการที่พบบ่อยที่สุดในผู้ป่วยคือ {sym.lower()}")
        if top_exp:
            lines.append(
                f"การวิเคราะห์ทางระบาดวิทยาพบว่า {top_exp.lower()} "
                f"เป็นปัจจัยเสี่ยงที่สำคัญที่สุด (p < 0.05)"
            )
        for line in lines:
            _para(doc, line)

    doc.add_paragraph()

    # ── SECTION 2: TIME DISTRIBUTION ─────────────────────────────────────────
    _heading(doc, s("s2"))

    # Timeline stats sub-table
    if time.get("first_onset"):
        dur_d = time.get("duration_days")
        missing = time.get("cases_missing_date", 0)
        time_rows: list[tuple[str, str]] = [
            (s("first_onset"), time.get("first_onset", "—")),
            (s("peak_onset"),  time.get("peak_onset",  "—")),
            (s("last_onset"),  time.get("last_onset",  "—")),
            (s("duration"),    f"{dur_d} {s('days')}" if dur_d else "—"),
        ]
        if missing:
            time_rows.append((s("missing_onset"), f"{missing} {s('cases_lbl')}"))
        _kv_table(doc, time_rows)
        doc.add_paragraph()

    _chart(doc, _get_chart(charts, "epicurve"), s("fig_epicurve"))
    doc.add_paragraph()

    # ── SECTION 3: PERSON CHARACTERISTICS ────────────────────────────────────
    _heading(doc, s("s3"))
    demo = pers.get("demographics", {})

    # 3.1 Sex
    sex_rows = demo.get("sex", [])
    if sex_rows:
        _heading(doc, s("s3_1"), level=2)
        _data_table(doc, [s("sex"), s("cases"), s("total"), s("ar")], [
            [r.get("sex", "—"), r.get("cases", 0), r.get("total", 0),
             f"{_fmt(r.get('attack_rate'), 1)}%"]
            for r in sex_rows
        ])
        doc.add_paragraph()

    # 3.2 Age group + pyramid
    age_rows = demo.get("age_group", [])
    if age_rows:
        _heading(doc, s("s3_2"), level=2)
        _data_table(doc, [s("age_group"), s("cases"), s("total"), s("ar")], [
            [r.get("age_group", "—"), r.get("cases", 0), r.get("total", 0),
             f"{_fmt(r.get('attack_rate'), 1)}%"]
            for r in age_rows
        ])
        doc.add_paragraph()

    _chart(doc, _get_chart(charts, "age_sex_pyramid"), s("fig_pyramid"))
    doc.add_paragraph()

    # 3.3 Other demographics (occupation, nationality, …)
    other_demo_vars = [v for v in ("occupation", "nationality") if v in demo]
    if other_demo_vars:
        _heading(doc, s("s3_3"), level=2)
        for var in other_demo_vars:
            var_rows = demo[var]
            label_key = var if var in ("occupation", "nationality") else "location"
            doc.add_paragraph(s(label_key).title(), style="Heading 3")
            _data_table(doc, [s(label_key), s("cases"), s("total"), s("ar")], [
                [r.get(var, "—"), r.get("cases", 0), r.get("total", 0),
                 f"{_fmt(r.get('attack_rate'), 1)}%"]
                for r in var_rows
            ])
            doc.add_paragraph()

    # 3.4 Symptoms
    symptoms = pers.get("symptoms", [])
    if symptoms:
        _heading(doc, s("s3_4"), level=2)
        _data_table(doc, [s("symptom"), s("cases"), s("pct_cases")], [
            [sym.get("symptom", "—"), sym.get("cases_with_symptom", 0),
             f"{_fmt(sym.get('percentage'), 1)}%"]
            for sym in symptoms
        ])
        doc.add_paragraph()
        _chart(doc, _get_chart(charts, "symptoms"), s("fig_symptoms"))
        doc.add_paragraph()

    # 3.5 Outcomes
    outcomes = pers.get("outcomes", [])
    if outcomes:
        _heading(doc, s("s3_5"), level=2)
        _data_table(doc, [s("outcome"), s("cases"), s("pct")], [
            [o.get("outcome", "—"), o.get("cases", 0), f"{_fmt(o.get('percentage'), 1)}%"]
            for o in outcomes
        ])
        doc.add_paragraph()

    # ── SECTION 4: PLACE DISTRIBUTION ────────────────────────────────────────
    place_tables = plc.get("tables", {})
    if place_tables:
        _heading(doc, s("s4"))
        for var, var_rows in place_tables.items():
            _heading(doc, var.replace("_", " ").title(), level=2)
            _data_table(
                doc,
                [s("location"), s("cases"), s("non_cases"), s("unknown"), s("total"), s("ar")],
                [
                    [
                        row.get(var, row.get("location", "—")),
                        row.get("cases", 0),
                        row.get("non_cases", 0),
                        row.get("unknown", 0),
                        row.get("total", 0),
                        f"{_fmt(row.get('attack_rate'), 1)}%",
                    ]
                    for row in var_rows
                ],
            )
            doc.add_paragraph()

    # ── SECTION 5: EXPOSURE & RISK ANALYSIS ──────────────────────────────────
    _heading(doc, s("s5"))

    if analytic_norm:
        n_sig = sum(1 for r in analytic_norm if r.get("significant"))
        _para(doc, s("n_analyzed").format(n=len(analytic_norm), sig=n_sig))
        doc.add_paragraph()

        _chart(doc, _get_chart(charts, "attack_rates"), s("fig_ar"))
        doc.add_paragraph()
        _chart(doc, _get_chart(charts, "forest_plot"),  s("fig_forest"))
        doc.add_paragraph()

        _heading(doc, s("s5_rr"), level=2)
        headers = [
            s("exposure"),
            s("exp_cases"), s("exp_total"), s("ar_exp"),
            s("unexp_cases"), s("unexp_total"), s("ar_unexp"),
            s("rr"), s("ci_95"), s("p_val"), s("sig"),
        ]
        sig_col_idx = len(headers) - 1
        tbl_rows = []
        for r in analytic_norm:
            tb  = r.get("table") or {}
            ci  = f"{_fmt(r.get('ci_lower'))}–{_fmt(r.get('ci_upper'))}"
            tbl_rows.append([
                r.get("exposure", ""),
                tb.get("cases_exposed",   "—"),
                tb.get("total_exposed",   "—"),
                f"{_fmt(r.get('ar_exposed'),   1)}%",
                tb.get("cases_unexposed", "—"),
                tb.get("total_unexposed", "—"),
                f"{_fmt(r.get('ar_unexposed'), 1)}%",
                _fmt(r.get("estimate")),
                ci,
                _fmt_p(r.get("p_value")),
                "Yes*" if r.get("significant") else "No",
            ])
        _data_table(doc, headers, tbl_rows, sig_col=sig_col_idx)
        _para(doc, s("sig_note"), italic=True, size_pt=9)
        doc.add_paragraph()
    else:
        _para(doc, s("no_analytic"))

    # ── SECTION 6: CONCLUSIONS ────────────────────────────────────────────────
    _heading(doc, s("s6"))
    sig_list = [r for r in analytic_norm if r.get("significant")]

    if sig_list:
        _para(doc, s("concl_sig").format(n=len(sig_list)))
        for r in sig_list:
            doc.add_paragraph(
                s("rr_bullet").format(
                    exposure=r.get("exposure", ""),
                    rr=_fmt(r.get("estimate")),
                    lo=_fmt(r.get("ci_lower")),
                    hi=_fmt(r.get("ci_upper")),
                    p=_fmt_p(r.get("p_value")),
                ),
                style="List Bullet",
            )
    else:
        _para(doc, s("no_sig"))

    doc.add_paragraph()
    _para(doc, s("disclaimer"), italic=True, size_pt=9, color=RGBColor(0x6B, 0x72, 0x80))

    doc.save(str(output_path))
    return output_path
